---@type LazySpec
return {
	"AstroNvim/astrocommunity",
	{ import = "astrocommunity.pack.docker" },
	{ import = "astrocommunity.pack.full-dadbod" },
	{ import = "astrocommunity.pack.go" },
	{ import = "astrocommunity.pack.godot" },
	{ import = "astrocommunity.pack.json" },
	{ import = "astrocommunity.pack.lua" },
	{ import = "astrocommunity.pack.markdown" },
	{ import = "astrocommunity.pack.proto" },
	{ import = "astrocommunity.pack.python" },
	{ import = "astrocommunity.pack.rust" },
	{ import = "astrocommunity.pack.sql" },
	{ import = "astrocommunity.pack.templ" },
	{ import = "astrocommunity.pack.terraform" },
	{ import = "astrocommunity.pack.toml" },
	{ import = "astrocommunity.pack.typescript" },
	{ import = "astrocommunity.pack.vue" },
	{ import = "astrocommunity.pack.xml" },
	{ import = "astrocommunity.pack.yaml" },
	{ import = "astrocommunity.programming-language-support.rest-nvim" },
	{ import = "astrocommunity.markdown-and-latex.render-markdown-nvim" },
	{ import = "astrocommunity.completion.tabnine-nvim" },
	{ import = "astrocommunity.note-taking.obsidian-nvim" },
	{ import = "astrocommunity.git.fugit2-nvim" },
	{ import = "astrocommunity.utility.noice-nvim" },
	{ import = "astrocommunity.colorscheme.catppuccin" },
	-- import/override with your plugins folder
}
