return {}

-- return {
-- 	"obsidian-nvim/obsidian.nvim",
-- 	version = "*", -- recommended, use latest release instead of latest commit
-- 	lazy = true,
-- 	cmd = {
-- 		"ObsidianOpen",
-- 		"ObsidianQuickSwitch",
-- 		"ObsidianNew",
-- 		"ObsidianSearch",
-- 		"ObsidianTemplate",
-- 		"ObsidianToday",
-- 		"ObsidianTomorrow",
-- 		"ObsidianYesterday",
-- 	},
-- 	ft = "markdown",
-- 	-- Replace the above line with this if you only want to load obsidian.nvim for markdown files in your vault:
-- 	-- event = {
-- 	--   -- If you want to use the home shortcut '~' here you need to call 'vim.fn.expand'.
-- 	--   -- E.g. "BufReadPre " .. vim.fn.expand "~" .. "/my-vault/*.md"
-- 	--   -- refer to `:h file-pattern` for more examples
-- 	--   "BufReadPre path/to/my-vault/*.md",
-- 	--   "BufNewFile path/to/my-vault/*.md",
-- 	-- },
-- 	dependencies = {
-- 		-- Required.
-- 		"nvim-lua/plenary.nvim",
--
-- 		-- see below for full list of optional dependencies 👇
-- 	},
-- 	opts = {
-- 		completion = {
-- 			nvim_cmp = false,
-- 			blink = true,
-- 		},
-- 		workspaces = {
-- 			{
-- 				name = "bloomberg_tao",
-- 				path = "~/Documents/bloomberg_tao/",
-- 			},
-- 		},
-- 		templates = {
-- 			folder = "templates",
-- 			date_format = "%Y-%m-%d",
-- 			time_format = "%H:%M",
-- 			-- A map for custom variables, the key should be the variable and the value a function
-- 			substitutions = {},
-- 		},
-- 		picker = {
-- 			name = "snacks.pick",
-- 		},
-- 		mappings = {
-- 			-- Overrides the 'gf' mapping to work on markdown/wiki links within your vault.
-- 			["gf"] = {
-- 				action = function()
-- 					return require("obsidian").util.gf_passthrough()
-- 				end,
-- 				opts = { noremap = false, expr = true, buffer = true },
-- 			},
-- 			-- Toggle check-boxes.
-- 			["<leader>ch"] = {
-- 				action = function()
-- 					return require("obsidian").util.toggle_checkbox()
-- 				end,
-- 				opts = { buffer = true },
-- 			},
-- 			-- Smart action depending on context: follow link, show notes with tag, or toggle checkbox.
-- 			["<cr>"] = {
-- 				action = function()
-- 					return require("obsidian").util.smart_action()
-- 				end,
-- 				opts = { buffer = true, expr = true },
-- 			},
-- 		},
-- 	},
-- }
